id: IF34FAB4A
ocr_import_info:
  timestamp: '2023-06-28T16:17:44.984862+00:00'
  batch_id: batch-afa7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 19:17:07.154272+00:00
last_modified: 2023-06-28 19:17:07.154278+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM2694
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM2694
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་སྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9140222440841479
  ocr_word_median_confidence_index: 0.978009
bases:
  I1NLM2694_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM2694_001
      total_pages: 234
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM2694_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.978009
      ocr_word_mean_confidence_index: 0.9140222440841479
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
